version: "3.9"
services:
  bot:
    build: .
    environment:
      - PREFIX
      - DISCORD_TOKEN
      - MONGO_URL=mongodb://mongo:27017
      - SERVER_NAME
      - WATCH_CHANNEL
      - COMMAND_CHANNEL
      - REDIS_URL=redis://redis:6379
    depends_on:
    - redis
    - mongo
  mongo:
    image: "mongo"
    ports:
    - 27017:27017
    volumes:
      - 'mongo_data:/data/db'
  redis:
    image: redis:4.0-alpine
volumes:
  mongo_data:
